import { db } from "@/lib/prisma";
import Link from "next/link";
import Image from "next/image";
import { Card, CardContent } from "@/components/ui/card";
import { Calendar } from "lucide-react";

export const dynamic = "force-dynamic";

export default async function BlogPage() {
  const posts = await db.blogPost.findMany({
    orderBy: { createdAt: "desc" }
  });

  return (
    <div className="container mx-auto py-12 px-4 max-w-6xl min-h-screen">
      <div className="text-center mb-16 space-y-4">
        <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight">Career Advice Blog</h1>
        <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
          Daily insights and strategies generated by SPY AI to help you land your dream job and accelerate your career.
        </p>
      </div>

      {posts.length === 0 ? (
        <div className="text-center text-muted-foreground py-12">
          <p>No blog posts yet. Check back tomorrow!</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {posts.map((post) => (
            <Link key={post.id} href={\`/blog/\${post.id}\`} className="group">
              <Card className="overflow-hidden border-border/50 h-full hover:shadow-lg transition-all card-lift">
                <div className="relative w-full h-48 overflow-hidden bg-muted">
                  <Image 
                    src={post.imageUrl} 
                    alt={post.title} 
                    fill
                    className="object-cover group-hover:scale-105 transition-transform duration-500"
                  />
                </div>
                <CardContent className="p-6 flex flex-col justify-between h-[calc(100%-12rem)]">
                  <div>
                    <div className="flex items-center text-xs text-muted-foreground mb-3 font-medium">
                      <Calendar className="mr-2 h-3 w-3" />
                      {new Date(post.createdAt).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}
                    </div>
                    <h2 className="text-xl font-bold mb-2 group-hover:text-primary transition-colors line-clamp-2">
                      {post.title}
                    </h2>
                    <p className="text-muted-foreground text-sm line-clamp-3">
                      {post.content.replace(/[#*`]/g, "") /* Strip basic markdown for preview */}
                    </p>
                  </div>
                  <div className="mt-4 pt-4 border-t text-sm font-semibold text-primary">
                    Read Article →
                  </div>
                </CardContent>
              </Card>
            </Link>
          ))}
        </div>
      )}
    </div>
  );
}
